### ISSUE TITLE
Parallelize predictions with static scheduling

### ISSUE THREAD

**Issue by NicolasHug** [ogrisel/pygbm#48]
Not sure if this will have a high impact on the time, but in predictions functions we could replace the parallel loop over all samples

```python
for i in prange(numeric_data.shape[0]):
```

to a static scheduling to take advantage of the cache.

This is probably only going to be significant if `scoring is not None` because in this case `_predict_binned` will be called at every iteration.

**Comment by ogrisel** [comment]
If you implement this please add a dedicated benchmark script for predictions to the `benchmarks/` folder.

**Comment by ogrisel** [comment]
You can also compare prediction time to LightGBM there.
