### ISSUE TITLE
Passing pre-binned data to `fit()`

### ISSUE THREAD

**Issue by NicolasHug** [ogrisel/pygbm#68]
I think that it is not possible to pass pre-binned data into `fit()`, or at least that results may not be as expected.

This is the case both in the current implementation, and also with the changes in #65.

Let's say we pre-bin `X` into `X_binned`:

```python
X_binned = initial_mapper.fit_transform(X)
```

and then call `fit(X_binned)`.

One might expect `predict(X)` to output the same as `predict_binned(X_binned)`, but that's not the case.

The reason is that in `fit()` the predictor is built with

```python
predictor = grower.make_predictor(bin_thresholds=self.bin_mapper_.bin_thresholds_)
```

and despite the idempotence of the mapper, `self.bin_mapper_.bin_thresholds_` is completely different from `initial_mapper.bin_thresholds_`.

* Do we want to raise an error if a uint8 array is passed to `fit` to avoid confusion?
* Do we want to allow passing pre-binned data and bypass the mapping in `fit()`? That would require passing `bin_thresholds` to `fit()` I think.

I'd go for the first option.

------------

I'm also thinking about adding this test to clarify the behavior. It passes on #65 branch:

```python
    X, y = make_regression()
    gbdt = GradientBoostingRegressor(scoring=None, random_state=0)
    mapper = BinMapper(random_state=0)
    X_binned = mapper.fit_transform(X)


    with pytest.raises(AssertionError):
        gbdt.fit(X_binned, y)
        np.testing.assert_array_almost_equal(gbdt.predict(X),
                                             gbdt.predict(X_binned))

    pred_X = gbdt.fit(X, y).predict(X)
    pred_X_binned = gbdt.fit(X_binned, y).predict(X_binned)
    np.testing.assert_array_almost_equal(pred_X, pred_X_binned)
```

**Comment by ogrisel** [comment]
What we could do is:

- if GradientBoostingClassifier.fit is passed uint8 data, it is considered pre-binned (not additional BinMapper involved)
- predicting on numerical data (any dtype that is not uint8) raises an informative `TypeError` stating it's not possible to use this model on non-binned numerical data.

**Comment by ogrisel** [comment]
That would imply making it possible to have:

```python
predictor = grower.make_predictor(bin_thresholds=None)
```

**Comment by NicolasHug** [comment]
Yeah I think that's a good idea.

So we'd also need a `fit_X_is_binned_` attribute right? Because `predict()` must accept both `uint8` and `float32`, as the early stopping checks are done with binned data that ais `uint8`.

**Comment by ogrisel** [comment]
We can just check that `self` has no `bin_mapper_` attribute.
