### ISSUE TITLE
Status of this project?

### ISSUE THREAD

**Issue by jondoering** [ogrisel/pygbm#94]
Hi, 
Are people still working on this project? Is this going anywhere? If not, what were the issues?
Just wondering, saw that latest commit is >6 month, but it's such a cool project. 

Thanks, 
Jonathan

**Comment by NicolasHug** [comment]
Hi @jondoering 	, we implemented a Cython-based version of pygbm into scikit-learn and it's been released in scikit-learn 0.21.

Next version (0.22) will have additional features including support for infinite values, support for missing values.

I guess we will continue to fix bugs here, but we're currently working on improving the scikit-learn version, not pygbm.

**Comment by jondoering** [comment]
@NicolasHug cool! Thanks for the quick answer. I will check the scikit-learn version!
